on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      with:
        FTP_SERVER: 54.180.79.66
        FTP_USERNAME: root@54.180.79.66
        FTP_PASSWORD: ${{ secrets.password }}
        PORT: 54198
        REMOTE_DIR: /usr/local/lsws/wordpress/wp-content/plugins/simply-static/static-files/
        METHOD: sftp
